[package]
name = "pobsdlib"
version = "0.1.0"
#edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "0.9.4"
serde_json = "0.9.4"
serde_derive = "0.9.4"
